### ISSUE TITLE
reject . in new project names

### ISSUE THREAD

**Issue by benatkin** [ibdknox/lein-noir#5]
I tried using a dot in a project name (`lein noir new sheet.io`) and `lein run` didn't work. After I deleted it and created it with `sheet-io` as the name (a dash instead of the dot) it worked. Rejecting names containing a dot would help some people who are new to clojure out.

**Comment by Raynes** [comment]
lein-noir will become a [lein-newnew](https://github.com/Raynes/lein-newnew) template soon. Could you check if the same problem applies to it and perhaps create an issue there?

**Comment by ibdknox** [comment]
lein-newnew'd so as long as it works there, everything should be fine
